In [53]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

iris=load_iris()
X=iris.data
y=iris.target

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=4)

def knn(X_train,X_test,y_train,k):
    dist=np.sqrt(np.sum((X_train-X_test)**2,axis=1))
    sorted_dist=np.argsort(dist)
    k_nearest_neighbors=sorted_dist[:k]
    count=np.bincount(y_train[k_nearest_neighbors])
    return np.argmax(count)

y_pred=[]
for i in range(len(X_test)):
    y_pred.append(knn(X_train,X_test[i],y_train,5))
y_pred=np.array(y_pred)
print("Confusion Matrix:")
print(confusion_matrix(y_test,y_pred))
print("Accuracy:")
print(accuracy_score(y_test,y_pred))

Confusion Matrix:
[[18  0  0]
 [ 0  7  1]
 [ 0  0 12]]
Accuracy:
0.9736842105263158
