### K center objective value 

In [53]:
from sklearn.datasets import load_digits
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

np.random.seed(69)
ds=load_digits()
arr=ds["data"]


def kcenter(k,arr):
    n,d=arr.shape
    centers=arr[np.random.choice(n,k,replace=False)]
    distances=np.zeros((n,k))
    while True:
        for i in range(n):
            for j in range(k):
                    distances[i][j]=np.linalg.norm(arr[i,:]-centers[j])
        labels=np.argmin(distances,axis=1)
        new_centers = np.zeros_like(centers)
        for i in range(k):
            assigned_points = arr[labels == i]
            new_centers[i] = assigned_points[np.argmax(np.linalg.norm(assigned_points - centers[i], axis=1))]

        if np.max(np.min(np.linalg.norm(arr[:, np.newaxis, :] - new_centers, axis=2), axis=1)) >= np.max(np.min(distances, axis=1)):
            break
        centers=new_centers.copy()
    # for i in range(len(centers)):
    #     plt.subplot(2,5,i+1)
    #     plt.imshow(centers[i].reshape(8,8),cmap=plt.cm.binary)
    #     plt.axis("off")
    # plt.show()
    all_costs=[]
    for i in range(k):
            assigned_points = arr[labels == i]
            all_costs.append(np.max(np.linalg.norm(assigned_points - centers[i], axis=1)))
    
    cluster_wise_points=[]
    for i in range(k):
        cluster_wise_points.append((arr[labels == i]))
    return  np.max(all_costs),cluster_wise_points
objective,cluster_wise_points_kcenter=kcenter(10,arr)
print("objective valve:",objective)


objective valve: 52.06726418777925


### K means clustering's cluster wise points 

In [54]:
def kmeans(k,arr,iter):
    n,d=arr.shape
    distances=np.zeros((n,k))
    centroids=arr[np.random.choice(n,k,replace=False)]
    
    for m in range(iter):
        for i in range(n):
            for j in range(k):
                distances[i][j]=np.linalg.norm(arr[i,:]-centroids[j])
        labels=np.argmin(distances,axis=1)
        for j in range(k):
            centroids[j]=np.mean(arr[labels==j],axis=0)
    cluster_wise_points=[]
    for i in range(k):
        cluster_wise_points.append((arr[labels == i]))
    return cluster_wise_points
cluster_wise_points_kmeans=kmeans(10,arr,100)

### Creating a 10x10 Matrix and updating i,j element of list by len of intersection set of ndarry

In [55]:
matrix=np.zeros((10,10))
for i in range(10):
    for j in range(10):
        matrix[i][j]+=len(set(cluster_wise_points_kmeans[i].tolist()[0]).intersection(cluster_wise_points_kcenter[j].tolist()[0]))
print(matrix)

[[13. 13. 13. 12. 14. 14. 12. 12. 12. 12.]
 [15. 16. 14. 13. 13. 16. 14. 13. 13. 13.]
 [15. 15. 13. 12. 13. 15. 13. 13. 12. 13.]
 [12. 13. 12. 12. 12. 14. 12. 12. 12. 12.]
 [12. 13. 13. 11. 12. 14. 12. 12. 14. 12.]
 [15. 16. 15. 14. 14. 17. 15. 14. 14. 14.]
 [12. 13. 12. 11. 11. 14. 12. 12. 12. 12.]
 [11. 12. 11. 11. 10. 13. 11. 10. 11. 12.]
 [12. 13. 12. 14. 12. 14. 13. 11. 11. 11.]
 [13. 14. 15. 12. 13. 15. 13. 12. 13. 12.]]
