In [11]:
from sklearn.datasets import load_digits
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
import warnings
warnings.filterwarnings('ignore')

digits = load_digits()
X=digits.data
y=digits.target

for img in X:
    gaussian_array = np.random.normal(0, 1, (img.shape))
    img = img + gaussian_array

kmeans = KMeans(n_clusters=10, random_state=0).fit(X)
y_pred = kmeans.predict(X)
accuracy = np.sum(y_pred == y)/len(y)

print("Accuracy: ", accuracy)
print("confusion matrix: \n", confusion_matrix(y, y_pred))

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

# kmeans on pca
kmeans = KMeans(n_clusters=10, random_state=0).fit(X_pca)
y_pred = kmeans.predict(X_pca)
accuracy = np.sum(y_pred == y)/len(y)

print("After applying PCA")
print("Accuracy: ", accuracy)
print("confusion matrix: \n", confusion_matrix(y, y_pred))


Accuracy:  0.015581524763494713
confusion matrix: 
 [[  1   0   0   0   0 177   0   0   0   0]
 [  0   1   1   0   0   0  55  99  24   2]
 [  0  13   0   2   3   1   2   8 148   0]
 [  0 154   2  13   7   0   0   7   0   0]
 [163   0   0   0   7   0   7   4   0   0]
 [  2   0 136  43   0   0   0   0   0   1]
 [  0   0   0   0   0   1   1   2   0 177]
 [  0   0   0   0 177   0   0   2   0   0]
 [  0   2   4  53   5   0   5 100   3   2]
 [  0   6   6 139   7   0  20   2   0   0]]
after applying PCA
Accuracy:  0.1318864774624374
confusion matrix: 
 [[160   4   1   1   0   0   0   0  12   0]
 [  0   7  28   3   9   0   0  86   0  49]
 [  0   4  36   0  12   0 113   0   0  12]
 [  0  21  10   0  13  89  50   0   0   0]
 [  0   0   0 144   3   0   0   5  24   5]
 [  5  49  44   2  26   0   4   0   5  47]
 [  8   0   0  21   0   0   0   0 150   2]
 [  0   0   1   1 117   0   0  21   0  39]
 [  0  10  71   1  25   0   3   4   0  60]
 [  0  78  16   0   9  58   8   0   1  10]]
